### ISSUE TITLE
Class 'Tymon\JWTAuth\Providers\AbstractServiceProvider' not found

### ISSUE THREAD

**Issue by nemerki** [rluders/oc-jwtauth-plugin#56]
Hi,

I'm t install the plugin from the October CMS Marketplace and get this error:

(1/1) FatalThrowableErrorClass 'Tymon\JWTAuth\Providers\AbstractServiceProvider' not found
--
in AuthServiceProvider.php line 12
at require_once()in ClassLoader.php line 130
at ClassLoader->includeClass('RLuders\\JWTAuth\\Providers\\AuthServiceProvider', 'plugins/rluders/jwtauth/providers/AuthServiceProvider.php')in ClassLoader.php line 99
at ClassLoader->load('RLuders\\JWTAuth\\Providers\\AuthServiceProvider')
at spl_autoload_call('RLuders\\JWTAuth\\Providers\\AuthServiceProvider')in Application.php line 635
at Application->resolveProvider('RLuders\\JWTAuth\\Providers\\AuthServiceProvider')in Application.php line 582
at Application->register('RLuders\\JWTAuth\\Providers\\AuthServiceProvider')in Plugin.php line 79
at Plugin->register()in PluginManager.php line 251
at PluginManager->registerPlugin(object(Plugin), 'RLuders.JWTAuth')in PluginManager.php line 185
at PluginManager->registerAll()in ServiceProvider.php line 51
at ServiceProvider->register()in Application.php line 586
at Application->register(object(ServiceProvider))in ProviderRepository.php line 75

**Comment by rluders** [comment]
Hi, @nemerki

This problem is directly related to [this issue](https://github.com/rluders/oc-jwtauth-plugin/issues/53). I had to update the plugin dependencies to match the OctoberCMS release with Laravel 6, but now, looks like we are facing some issues related to OctoberCMS Marketplace itself.

I was talking to some people, including Luke Towers, and there are other people complaining that the Marketplace isn't downloading some plugin's dependencies.

So, for now, what I can advise you is to wait till they fix it. I'll keep following its resolution, and as soon I get some update, I'll test it and let u know about it.

Sorry about the inconvenience, but at this moment, doesn't seem that I can do much more about it.

**Comment by nemerki** [comment]
can i download plugin dependencies from github ?  or can you send me dependencies zip or another way

**Comment by rluders** [comment]
Yes. You can install the plugin directly from the Github repository. Just download it from [here](https://github.com/rluders/oc-jwtauth-plugin/releases/tag/v1.4.4) and put its content in the `rluders/jwauth` plugins folder.

Then, you will have to execute the composer to install the dependencies. If you installed the OctoberCMS with `composer create` command, you can go back to the project root and execute `composer update`, if it is not the case, you can execute the `composer install` from the jwtauth plugin folder.

It should install all the plugins dependency and you are good to go.

**Comment by rluders** [comment]
I'm closing this issue, and handling it from it's duplicated on #53
