### ISSUE TITLE
Fork for Winter CMS

### ISSUE THREAD

**Issue by josephcrowell** [rluders/oc-jwtauth-plugin#58]
I have created a fork where I have gotten this plugin working with the native Winter (formerly RainLab) plugins and core modules instead of their compatibility aliases.

https://github.com/josephcrowell/wn-jwtauth-plugin

I am good to maintain if you don't want to maintain a fork for Winter, but if you were going over to Winter any way, you can pull this in (probably as a new repo since the name is changed) where I've done the work for you.

**Comment by rluders** [comment]
Hi, @josephcrowell... 

I'm sorry... I'm a little bit away from OctoberCMS Community these last months. Did the project got split into two different projects, right? I need to check, I guess that I can't just "drop" the support to OctoberCMS, but I would like to keep support for both.

Do you think that we can do it in the same repository? Maybe different branches... Does it make sense? Otherwise, I'm totally fine with you continue maintain it in a separated repo. :)

**Comment by rluders** [comment]
Now that I catch up on what happened. I'll definitely aim to WinterCMS... So, I'll be happy to accept a PR, and also rename the repository to `wn-jwtauth-plugin` :)
